language: node_js
node_js:
- 'node'
- 'iojs'
script: |
  npm test
  #if [[ $TRAVIS_JOB_NUMBER = *.1 ]]
  #then
    #npm test && npm run test-browser-sauce
  #else
    #npm test
  #fi
env:
  global:
  # Sauce Labs
  - secure: JhPSTL1BydtnQSiBNCEIdX7Ex1YMCBGPctAPyPZw1b249A/SQMceuofNz9+JDwXxNXaoxP4cK0t3yAu6zWeQe8a6GpoT7pnOC0ODG5o5M0LOsJa6K1s2kPT7+z6uTwt9e4qFOyCLfGpASID4SquvnlOWaeriVfdcTGrPTjb2oZI=
  - secure: Sctvn2AgQ5ZCUTqM8qijl0x2tjbhrfjrMpNh2I0CiTvsKXpao2EgWHQjXm/glNovy040522r4L4kfKRE/7Eg/opBePH8vU4nBQc8lyMWarauLtiURxGdiJYDoyrbI8Sp2u9Fe/CleiCvQLAHWTsM2rCWYcKylcU3axvmI3AW108=
